## Universidad Autonoma de Aguascalientes
## Departamento: Ciencias de la computación
## Carrera: Ingenieria en computacion inteligente
### Curso: Inteligencia Artificial (El perceptron Frank Rosenblatt)
### Maestro: Dr. Francisco Javier Luna Rosas
### Alumno: Paola Montserrat Osorio Garcia 
### Semestre: Agosto_Diciembre 

# PRACTICA No. 4 El perceptron de Frank Rosenblatt entrenado

### Un perceptrón es un tipo de modelo de red neuronal muy simple, utilizando principalmente para problemas de clasificacion binaria. Fue desarrollado en 1958 por Frank Rosenblatt y  es considerado  uno de los primeros algoritmos de aprendizaje supervisado.

### Un perceptrón toma un conjunto de entradas, las procesa meidante una serie de operadores matematicos y produce una salida que puede ser 0 o 1, dependiendo de su el resultado final supera un umbral predeterminado.

### EJEMPLO: Determinar si se le aprueba o no una tarjeta de credito a un cliente, considerando la edad y  el ahorro que tiene en su cuenta bancaria.

# Paso 1: Importar librerias necesarias

In [1]:
import numpy as np # type: ignore
import matplotlib.pyplot as plt # type: ignore

# Paso 2: Generar los datos

In [2]:
personas = np.array ([[0.3,0.4],[0.4,0.3],
                     [0.3,0.2],[0.4,0.1],
                     [0.5,0.4],[0.4,0.8],
                     [0.6,0.8],[0.5,0.6],
                     [0.7,0.6],[0.8,0.5]])

# Paso 3: Definir las clases : 1 : aprobado, 0 : denegado

In [3]:
clases = np.array ([0,0,0,0,0,1,1,1,1,1])

# Paso 4: Definir la funcion de activacion

In [4]:
# w1*x1 + w2*x2 + ... + wn*xn
def activacion (pesos, x, b):
    z = pesos * x
    if z.sum() + b > 0:
        return 1
    else:
        return 0

# Paso 5: Generamos los pesos y el bias

In [5]:
pesos = np.random.uniform(-1,1, size=2)
b = np.random.uniform(-1,1)
pesos, b, activacion (pesos, [ 0.5, 0.6 ], b)

(array([-0.59471253,  0.08616585]), 0.25125795689928143, 1)

# Paso 6: Implementamos el algoritmo en el perceptron

In [6]:
pesos = np.random.uniform(-1,1,size=2)
b = np.random.uniform(-1,1)
tasa_de_aprendiaje = 0.01
epocas = 100

#Ciclo de entrenamiento

for epoca in range(epocas):
    error_total = 0
    for i in range (len(personas)):
        prediccion = activacion(pesos,personas[i], b)
        error = clases[i] - prediccion
        error_total += error**2
        pesos[0] += tasa_de_aprendiaje * personas[i][0] * error
        pesos[1] += tasa_de_aprendiaje * personas[i][1] * error
        b += tasa_de_aprendiaje * error
    print (error_total, end=" ")


2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 3 2 2 1 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2 2 2 1 2 2 2 1 2 2 2 2 1 2 2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

# Paso 7: Probar el algoritmo

In [7]:
pesos,b,activacion(pesos, [0.3,0.4],b)

(array([-0.16143759,  0.85951165]), -0.2978846721535193, 0)

In [8]:
pesos,b,activacion(pesos, [0.8,0.5],b)

(array([-0.16143759,  0.85951165]), -0.2978846721535193, 1)

## Conclusiones

### En esta practica  entrenamos el algoritmo del perceptron para determinar si se aprueba o no una tarjeta de credito a un cliente, considerando la edad y el ahorro que tiene en su cuenta bancaria

## Referencias

### Russell S. J., Norving P. (2020).  Artificial Intelligence: A Modern Approach, Prentice - Hall, 4th Edition, Englewood Cliffs, NJ, 2020.

# Extra usando perceptron importado

In [9]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Perceptron

In [10]:
personas = np.array ([[0.3,0.4],[0.4,0.3],
                     [0.3,0.2],[0.4,0.1],
                     [0.5,0.4],[0.4,0.8],
                     [0.6,0.8],[0.5,0.6],
                     [0.7,0.6],[0.8,0.5]])

In [11]:
clases = np.array([0,0,0,0,0,1,1,1,1,1])

In [12]:
from sklearn.linear_model import Perceptron
perceptron = Perceptron().fit(personas,clases)
perceptron.predict([[0.3,0.4],[0.8,0.5]])

array([0, 1])